package pqt.dss.rfrt.model.vo;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;

import pqt.dss.rfrt.model.vo.common.DssReqResigTermHeaderView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 19 17:23:38 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssReqResigTermHeaderViewImpl extends ViewObjectImpl implements DssReqResigTermHeaderView {
    /**
     * This is the default constructor (do not remove).
     */
    public DssReqResigTermHeaderViewImpl() {
    }


    /**
     * Returns the variable value for VC_Current_Qtr.
     * @return variable value for VC_Current_Qtr
     */
    public Number getVC_Current_Qtr() {
        return (Number) ensureVariableManager().getVariableValue("VC_Current_Qtr");
    }

    /**
     * Sets <code>value</code> for variable VC_Current_Qtr.
     * @param value value to bind as VC_Current_Qtr
     */
    public void setVC_Current_Qtr(Number value) {
        ensureVariableManager().setVariableValue("VC_Current_Qtr", value);
    }

    /**
     * Returns the variable value for NVC_wfDocumentId.
     * @return variable value for NVC_wfDocumentId
     */
    public Number getNVC_wfDocumentId() {
        return (Number) ensureVariableManager().getVariableValue("NVC_wfDocumentId");
    }

    /**
     * Sets <code>value</code> for variable NVC_wfDocumentId.
     * @param value value to bind as NVC_wfDocumentId
     */
    public void setNVC_wfDocumentId(Number value) {
        ensureVariableManager().setVariableValue("NVC_wfDocumentId", value);
        
        this.exeViewCrieteria(value);
    }
    public void exeViewCrieteria(Number val) {
        ViewObject vo = this.getViewObject();
        ViewCriteria vc = this.getViewCriteria("NotificationViewCriteria");
        vo.applyViewCriteria(vc);
        vo.setNamedWhereClauseParam("NVC_wfDocumentId", val);
        vo.executeQuery();
    }

    /**
     * Returns the variable value for VC_Doc_No.
     * @return variable value for VC_Doc_No
     */
    public String getVC_Doc_No() {
        return (String) ensureVariableManager().getVariableValue("VC_Doc_No");
    }

    /**
     * Sets <code>value</code> for variable VC_Doc_No.
     * @param value value to bind as VC_Doc_No
     */
    public void setVC_Doc_No(String value) {
        ensureVariableManager().setVariableValue("VC_Doc_No", value);
    }

    public void rfrtSearchUser()
    {
                ViewCriteria vc = this.getViewCriteria("DssReqResigTermHeaderViewCriteria");
                this.applyViewCriteria(vc);
                 setWhereClause(null);
                 FacesContext fctx = FacesContext.getCurrentInstance();
                 ExternalContext ectx = fctx.getExternalContext();
                 HttpSession userSession = (HttpSession) ectx.getSession(false);
                 Object VUserID = userSession.getAttribute("pUserId") == null ? "0" : userSession.getAttribute("pUserId");
                 setWhereClause("exists\n" + 
                               " (select 1 \n" + 
                               "          from dss_sm_user_branch a\n" + 
                               "         where a.user_id_fk = "+ VUserID+"\n" + 
                               "           and a.branch_code = BRANCH_CODE_FK)");
                 //              setWhereClause("USER_ID_FK =" + VUserID);
                               executeQuery();
                           }

}

