package pqt.dss.rfrt.model.vo;


import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;

import pqt.dss.rfrt.model.eo.DssReqResigTermHeaderImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 03 16:30:21 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssReqResigTermHeaderViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_DSSREQRESIGTERMHEADER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ActiveConsultants,
        AgentNoFk,
        BranchCodeFk,
        BranchNotifIdFk,
        BranchStatus,
        CurrentQtr,
        DssNotifIdFk,
        DssStatus,
        EnterDate,
        JoiningDate,
        LastRankDate,
        LastUpdatedBy,
        LastUpdatedDate,
        ManagerIdFk,
        MonthSalaryDrawn,
        PersonType,
        RankCodeFk,
        RegionCodeFk,
        Remarks,
        RequestReason,
        RequestType,
        ResignationFile,
        ResignationLetter,
        RfrtHeaderIdPk,
        UserIdFk,
        YearToDate,
        RfrtDocNo,
        AgentStipend,
        WorkflowNotificationId,
        WorkflowStatus,
        GisLocationIdFk,
        PlanTransferDocNo,
        AgentName,
        AgentCode,
        QuarterBussPol,
        QuarterBuss,
        HalfyearBussPol,
        HalfyearBuss,
        YearlyBussPol,
        YearlyBuss,
        Designation,
        ReportingManagerName,
        BranchName,
        Region,
        DateOfJoing,
        RankDate,
        Portfolio,
        FileContentType,
        ActiveConsultant,
        ActiveManager,
        PlanTransferHdrIdFk,
        DssReqResigTermLineView,
        ResigTerminationPopList2,
        AgentManagPopList1,
        StipendPopList1,
        UserBranchDtlLovVo1,
        AgentDetailLovVo1,
        AccLocationLov;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVECONSULTANTS = AttributesEnum.ActiveConsultants.index();
    public static final int AGENTNOFK = AttributesEnum.AgentNoFk.index();
    public static final int BRANCHCODEFK = AttributesEnum.BranchCodeFk.index();
    public static final int BRANCHNOTIFIDFK = AttributesEnum.BranchNotifIdFk.index();
    public static final int BRANCHSTATUS = AttributesEnum.BranchStatus.index();
    public static final int CURRENTQTR = AttributesEnum.CurrentQtr.index();
    public static final int DSSNOTIFIDFK = AttributesEnum.DssNotifIdFk.index();
    public static final int DSSSTATUS = AttributesEnum.DssStatus.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int JOININGDATE = AttributesEnum.JoiningDate.index();
    public static final int LASTRANKDATE = AttributesEnum.LastRankDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int MANAGERIDFK = AttributesEnum.ManagerIdFk.index();
    public static final int MONTHSALARYDRAWN = AttributesEnum.MonthSalaryDrawn.index();
    public static final int PERSONTYPE = AttributesEnum.PersonType.index();
    public static final int RANKCODEFK = AttributesEnum.RankCodeFk.index();
    public static final int REGIONCODEFK = AttributesEnum.RegionCodeFk.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int REQUESTREASON = AttributesEnum.RequestReason.index();
    public static final int REQUESTTYPE = AttributesEnum.RequestType.index();
    public static final int RESIGNATIONFILE = AttributesEnum.ResignationFile.index();
    public static final int RESIGNATIONLETTER = AttributesEnum.ResignationLetter.index();
    public static final int RFRTHEADERIDPK = AttributesEnum.RfrtHeaderIdPk.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int YEARTODATE = AttributesEnum.YearToDate.index();
    public static final int RFRTDOCNO = AttributesEnum.RfrtDocNo.index();
    public static final int AGENTSTIPEND = AttributesEnum.AgentStipend.index();
    public static final int WORKFLOWNOTIFICATIONID = AttributesEnum.WorkflowNotificationId.index();
    public static final int WORKFLOWSTATUS = AttributesEnum.WorkflowStatus.index();
    public static final int GISLOCATIONIDFK = AttributesEnum.GisLocationIdFk.index();
    public static final int PLANTRANSFERDOCNO = AttributesEnum.PlanTransferDocNo.index();
    public static final int AGENTNAME = AttributesEnum.AgentName.index();
    public static final int AGENTCODE = AttributesEnum.AgentCode.index();
    public static final int QUARTERBUSSPOL = AttributesEnum.QuarterBussPol.index();
    public static final int QUARTERBUSS = AttributesEnum.QuarterBuss.index();
    public static final int HALFYEARBUSSPOL = AttributesEnum.HalfyearBussPol.index();
    public static final int HALFYEARBUSS = AttributesEnum.HalfyearBuss.index();
    public static final int YEARLYBUSSPOL = AttributesEnum.YearlyBussPol.index();
    public static final int YEARLYBUSS = AttributesEnum.YearlyBuss.index();
    public static final int DESIGNATION = AttributesEnum.Designation.index();
    public static final int REPORTINGMANAGERNAME = AttributesEnum.ReportingManagerName.index();
    public static final int BRANCHNAME = AttributesEnum.BranchName.index();
    public static final int REGION = AttributesEnum.Region.index();
    public static final int DATEOFJOING = AttributesEnum.DateOfJoing.index();
    public static final int RANKDATE = AttributesEnum.RankDate.index();
    public static final int PORTFOLIO = AttributesEnum.Portfolio.index();
    public static final int FILECONTENTTYPE = AttributesEnum.FileContentType.index();
    public static final int ACTIVECONSULTANT = AttributesEnum.ActiveConsultant.index();
    public static final int ACTIVEMANAGER = AttributesEnum.ActiveManager.index();
    public static final int PLANTRANSFERHDRIDFK = AttributesEnum.PlanTransferHdrIdFk.index();
    public static final int DSSREQRESIGTERMLINEVIEW = AttributesEnum.DssReqResigTermLineView.index();
    public static final int RESIGTERMINATIONPOPLIST2 = AttributesEnum.ResigTerminationPopList2.index();
    public static final int AGENTMANAGPOPLIST1 = AttributesEnum.AgentManagPopList1.index();
    public static final int STIPENDPOPLIST1 = AttributesEnum.StipendPopList1.index();
    public static final int USERBRANCHDTLLOVVO1 = AttributesEnum.UserBranchDtlLovVo1.index();
    public static final int AGENTDETAILLOVVO1 = AttributesEnum.AgentDetailLovVo1.index();
    public static final int ACCLOCATIONLOV = AttributesEnum.AccLocationLov.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssReqResigTermHeaderViewRowImpl() {
    }

    /**
     * Gets DssReqResigTermHeader entity object.
     * @return the DssReqResigTermHeader
     */
    public DssReqResigTermHeaderImpl getDssReqResigTermHeader() {
        return (DssReqResigTermHeaderImpl) getEntity(ENTITY_DSSREQRESIGTERMHEADER);
    }

    /**
     * Gets the attribute value for RFRT_HEADER_ID_PK using the alias name RfrtHeaderIdPk.
     * @return the RFRT_HEADER_ID_PK
     */
    public Number getRfrtHeaderIdPk() {
        return (Number) getAttributeInternal(RFRTHEADERIDPK);
    }

    /**
     * Sets <code>value</code> as attribute value for RFRT_HEADER_ID_PK using the alias name RfrtHeaderIdPk.
     * @param value value to set the RFRT_HEADER_ID_PK
     */
    public void setRfrtHeaderIdPk(Number value) {
        setAttributeInternal(RFRTHEADERIDPK, value);
    }

    /**
     * Gets the attribute value for AGENT_NO_FK using the alias name AgentNoFk.
     * @return the AGENT_NO_FK
     */
    public Number getAgentNoFk() {
        return (Number) getAttributeInternal(AGENTNOFK);
    }

    /**
     * Sets <code>value</code> as attribute value for AGENT_NO_FK using the alias name AgentNoFk.
     * @param value value to set the AGENT_NO_FK
     */
    public void setAgentNoFk(Number value) {
        setAttributeInternal(AGENTNOFK, value);
    }

    /**
     * Gets the attribute value for RANK_CODE_FK using the alias name RankCodeFk.
     * @return the RANK_CODE_FK
     */
    public String getRankCodeFk() {
        return (String) getAttributeInternal(RANKCODEFK);
    }

    /**
     * Sets <code>value</code> as attribute value for RANK_CODE_FK using the alias name RankCodeFk.
     * @param value value to set the RANK_CODE_FK
     */
    public void setRankCodeFk(String value) {
        setAttributeInternal(RANKCODEFK, value);
    }

    /**
     * Gets the attribute value for MANAGER_ID_FK using the alias name ManagerIdFk.
     * @return the MANAGER_ID_FK
     */
    public Number getManagerIdFk() {
        return (Number) getAttributeInternal(MANAGERIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER_ID_FK using the alias name ManagerIdFk.
     * @param value value to set the MANAGER_ID_FK
     */
    public void setManagerIdFk(Number value) {
        setAttributeInternal(MANAGERIDFK, value);
    }

    /**
     * Gets the attribute value for BRANCH_CODE_FK using the alias name BranchCodeFk.
     * @return the BRANCH_CODE_FK
     */
    public String getBranchCodeFk() {
        return (String) getAttributeInternal(BRANCHCODEFK);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCH_CODE_FK using the alias name BranchCodeFk.
     * @param value value to set the BRANCH_CODE_FK
     */
    public void setBranchCodeFk(String value) {
        setAttributeInternal(BRANCHCODEFK, value);
    }

    /**
     * Gets the attribute value for REGION_CODE_FK using the alias name RegionCodeFk.
     * @return the REGION_CODE_FK
     */
    public String getRegionCodeFk() {
        return (String) getAttributeInternal(REGIONCODEFK);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_CODE_FK using the alias name RegionCodeFk.
     * @param value value to set the REGION_CODE_FK
     */
    public void setRegionCodeFk(String value) {
        setAttributeInternal(REGIONCODEFK, value);
    }

    /**
     * Gets the attribute value for JOINING_DATE using the alias name JoiningDate.
     * @return the JOINING_DATE
     */
    public Date getJoiningDate() {
        return (Date) getAttributeInternal(JOININGDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOINING_DATE using the alias name JoiningDate.
     * @param value value to set the JOINING_DATE
     */
    public void setJoiningDate(Date value) {
        setAttributeInternal(JOININGDATE, value);
    }

    /**
     * Gets the attribute value for LAST_RANK_DATE using the alias name LastRankDate.
     * @return the LAST_RANK_DATE
     */
    public Date getLastRankDate() {
        return (Date) getAttributeInternal(LASTRANKDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_RANK_DATE using the alias name LastRankDate.
     * @param value value to set the LAST_RANK_DATE
     */
    public void setLastRankDate(Date value) {
        setAttributeInternal(LASTRANKDATE, value);
    }

    /**
     * Gets the attribute value for MONTH_SALARY_DRAWN using the alias name MonthSalaryDrawn.
     * @return the MONTH_SALARY_DRAWN
     */
    public Number getMonthSalaryDrawn() {
        return (Number) getAttributeInternal(MONTHSALARYDRAWN);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH_SALARY_DRAWN using the alias name MonthSalaryDrawn.
     * @param value value to set the MONTH_SALARY_DRAWN
     */
    public void setMonthSalaryDrawn(Number value) {
        setAttributeInternal(MONTHSALARYDRAWN, value);
    }

    /**
     * Gets the attribute value for CURRENT_QTR using the alias name CurrentQtr.
     * @return the CURRENT_QTR
     */
    public Number getCurrentQtr() {
        return (Number) getAttributeInternal(CURRENTQTR);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_QTR using the alias name CurrentQtr.
     * @param value value to set the CURRENT_QTR
     */
    public void setCurrentQtr(Number value) {
        setAttributeInternal(CURRENTQTR, value);
    }

    /**
     * Gets the attribute value for YEAR_TO_DATE using the alias name YearToDate.
     * @return the YEAR_TO_DATE
     */
    public Date getYearToDate() {
        return (Date) getAttributeInternal(YEARTODATE);
    }

    /**
     * Sets <code>value</code> as attribute value for YEAR_TO_DATE using the alias name YearToDate.
     * @param value value to set the YEAR_TO_DATE
     */
    public void setYearToDate(Date value) {
        setAttributeInternal(YEARTODATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AgentName.
     * @return the AgentName
     */
    public String getAgentName() {
        return (String) getAttributeInternal(AGENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AgentName.
     * @param value value to set the  AgentName
     */
    public void setAgentName(String value) {
        setAttributeInternal(AGENTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AgentCode.
     * @return the AgentCode
     */
    public String getAgentCode() {
        return (String) getAttributeInternal(AGENTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AgentCode.
     * @param value value to set the  AgentCode
     */
    public void setAgentCode(String value) {
        setAttributeInternal(AGENTCODE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute QuarterBussPol.
     * @return the QuarterBussPol
     */
    public Number getQuarterBussPol() {
        return (Number) getAttributeInternal(QUARTERBUSSPOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute QuarterBussPol.
     * @param value value to set the  QuarterBussPol
     */
    public void setQuarterBussPol(Number value) {
        setAttributeInternal(QUARTERBUSSPOL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute QuarterBuss.
     * @return the QuarterBuss
     */
    public Number getQuarterBuss() {
        return (Number) getAttributeInternal(QUARTERBUSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute QuarterBuss.
     * @param value value to set the  QuarterBuss
     */
    public void setQuarterBuss(Number value) {
        setAttributeInternal(QUARTERBUSS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HalfyearBussPol.
     * @return the HalfyearBussPol
     */
    public Number getHalfyearBussPol() {
        return (Number) getAttributeInternal(HALFYEARBUSSPOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HalfyearBussPol.
     * @param value value to set the  HalfyearBussPol
     */
    public void setHalfyearBussPol(Number value) {
        setAttributeInternal(HALFYEARBUSSPOL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HalfyearBuss.
     * @return the HalfyearBuss
     */
    public Number getHalfyearBuss() {
        return (Number) getAttributeInternal(HALFYEARBUSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HalfyearBuss.
     * @param value value to set the  HalfyearBuss
     */
    public void setHalfyearBuss(Number value) {
        setAttributeInternal(HALFYEARBUSS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute YearlyBussPol.
     * @return the YearlyBussPol
     */
    public Number getYearlyBussPol() {
        return (Number) getAttributeInternal(YEARLYBUSSPOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute YearlyBussPol.
     * @param value value to set the  YearlyBussPol
     */
    public void setYearlyBussPol(Number value) {
        setAttributeInternal(YEARLYBUSSPOL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute YearlyBuss.
     * @return the YearlyBuss
     */
    public Number getYearlyBuss() {
        return (Number) getAttributeInternal(YEARLYBUSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute YearlyBuss.
     * @param value value to set the  YearlyBuss
     */
    public void setYearlyBuss(Number value) {
        setAttributeInternal(YEARLYBUSS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Designation.
     * @return the Designation
     */
    public String getDesignation() {
        return (String) getAttributeInternal(DESIGNATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Designation.
     * @param value value to set the  Designation
     */
    public void setDesignation(String value) {
        setAttributeInternal(DESIGNATION, value);
    }


    /**
     * Gets the attribute value for the calculated attribute ReportingManagerName.
     * @return the ReportingManagerName
     */
    public String getReportingManagerName() {
        return (String) getAttributeInternal(REPORTINGMANAGERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ReportingManagerName.
     * @param value value to set the  ReportingManagerName
     */
    public void setReportingManagerName(String value) {
        setAttributeInternal(REPORTINGMANAGERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BranchName.
     * @return the BranchName
     */
    public String getBranchName() {
        return (String) getAttributeInternal(BRANCHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BranchName.
     * @param value value to set the  BranchName
     */
    public void setBranchName(String value) {
        setAttributeInternal(BRANCHNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Region.
     * @return the Region
     */
    public String getRegion() {
        return (String) getAttributeInternal(REGION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Region.
     * @param value value to set the  Region
     */
    public void setRegion(String value) {
        setAttributeInternal(REGION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DateOfJoing.
     * @return the DateOfJoing
     */
    public Date getDateOfJoing() {
        return (Date) getAttributeInternal(DATEOFJOING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DateOfJoing.
     * @param value value to set the  DateOfJoing
     */
    public void setDateOfJoing(Date value) {
        setAttributeInternal(DATEOFJOING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RankDate.
     * @return the RankDate
     */
    public Date getRankDate() {
        return (Date) getAttributeInternal(RANKDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RankDate.
     * @param value value to set the  RankDate
     */
    public void setRankDate(Date value) {
        setAttributeInternal(RANKDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Portfolio.
     * @return the Portfolio
     */
    public Number getPortfolio() {
        return (Number) getAttributeInternal(PORTFOLIO);
    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Portfolio.
     * @param value value to set the  Portfolio
     */
    public void setPortfolio(Number value) {
        setAttributeInternal(PORTFOLIO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FileContentType.
     * @return the FileContentType
     */
    public String getFileContentType() {
        return (String) getAttributeInternal(FILECONTENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_CONTENT_TYPE using the alias name FileContentType.
     * @param value value to set the FILE_CONTENT_TYPE
     */
    public void setFileContentType(String value) {
        setAttributeInternal(FILECONTENTTYPE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute ActiveConsultant.
     * @return the ActiveConsultant
     */
    public Number getActiveConsultant() {
        return (Number) getAttributeInternal(ACTIVECONSULTANT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActiveConsultant.
     * @param value value to set the  ActiveConsultant
     */
    public void setActiveConsultant(Number value) {
        setAttributeInternal(ACTIVECONSULTANT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActiveManager.
     * @return the ActiveManager
     */
    public Number getActiveManager() {
        return (Number) getAttributeInternal(ACTIVEMANAGER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActiveManager.
     * @param value value to set the  ActiveManager
     */
    public void setActiveManager(Number value) {
        setAttributeInternal(ACTIVEMANAGER, value);
    }

    /**
     * Gets the attribute value for PLAN_TRANSFER_HDR_ID_FK using the alias name PlanTransferHdrIdFk.
     * @return the PLAN_TRANSFER_HDR_ID_FK
     */
    public Number getPlanTransferHdrIdFk() {
        return (Number) getAttributeInternal(PLANTRANSFERHDRIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for PLAN_TRANSFER_HDR_ID_FK using the alias name PlanTransferHdrIdFk.
     * @param value value to set the PLAN_TRANSFER_HDR_ID_FK
     */
    public void setPlanTransferHdrIdFk(Number value) {
        setAttributeInternal(PLANTRANSFERHDRIDFK, value);
    }

    /**
     * Gets the attribute value for WORKFLOW_NOTIFICATION_ID using the alias name WorkflowNotificationId.
     * @return the WORKFLOW_NOTIFICATION_ID
     */
    public Number getWorkflowNotificationId() {
        return (Number) getAttributeInternal(WORKFLOWNOTIFICATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKFLOW_NOTIFICATION_ID using the alias name WorkflowNotificationId.
     * @param value value to set the WORKFLOW_NOTIFICATION_ID
     */
    public void setWorkflowNotificationId(Number value) {
        setAttributeInternal(WORKFLOWNOTIFICATIONID, value);
    }

    /**
     * Gets the attribute value for WORKFLOW_STATUS using the alias name WorkflowStatus.
     * @return the WORKFLOW_STATUS
     */
    public String getWorkflowStatus() {
        return (String) getAttributeInternal(WORKFLOWSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKFLOW_STATUS using the alias name WorkflowStatus.
     * @param value value to set the WORKFLOW_STATUS
     */
    public void setWorkflowStatus(String value) {
        setAttributeInternal(WORKFLOWSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GisLocationIdFk.
     * @return the GisLocationIdFk
     */
    public BigDecimal getGisLocationIdFk() {
        return (BigDecimal) getAttributeInternal(GISLOCATIONIDFK);
    }

    /**
     * Gets the attribute value for the calculated attribute PlanTransferDocNo.
     * @return the PlanTransferDocNo
     */
    public String getPlanTransferDocNo() {
        return (String) getAttributeInternal(PLANTRANSFERDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PlanTransferDocNo.
     * @param value value to set the  PlanTransferDocNo
     */
    public void setPlanTransferDocNo(String value) {
        setAttributeInternal(PLANTRANSFERDOCNO, value);
    }

    /**
     * Gets the attribute value for AGENT_STIPEND using the alias name AgentStipend.
     * @return the AGENT_STIPEND
     */
    public String getAgentStipend() {
        return (String) getAttributeInternal(AGENTSTIPEND);
    }

    /**
     * Sets <code>value</code> as attribute value for AGENT_STIPEND using the alias name AgentStipend.
     * @param value value to set the AGENT_STIPEND
     */
    public void setAgentStipend(String value) {
        setAttributeInternal(AGENTSTIPEND, value);
    }

    /**
     * Gets the attribute value for RFRT_DOC_NO using the alias name RfrtDocNo.
     * @return the RFRT_DOC_NO
     */
    public String getRfrtDocNo() {
        return (String) getAttributeInternal(RFRTDOCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RFRT_DOC_NO using the alias name RfrtDocNo.
     * @param value value to set the RFRT_DOC_NO
     */
    public void setRfrtDocNo(String value) {
        setAttributeInternal(RFRTDOCNO, value);
    }

    /**
     * Gets the attribute value for ACTIVE_CONSULTANTS using the alias name ActiveConsultants.
     * @return the ACTIVE_CONSULTANTS
     */
    public Number getActiveConsultants() {
        return (Number) getAttributeInternal(ACTIVECONSULTANTS);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_CONSULTANTS using the alias name ActiveConsultants.
     * @param value value to set the ACTIVE_CONSULTANTS
     */
    public void setActiveConsultants(Number value) {
        setAttributeInternal(ACTIVECONSULTANTS, value);
    }

    /**
     * Gets the attribute value for REQUEST_TYPE using the alias name RequestType.
     * @return the REQUEST_TYPE
     */
    public String getRequestType() {
        return (String) getAttributeInternal(REQUESTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_TYPE using the alias name RequestType.
     * @param value value to set the REQUEST_TYPE
     */
    public void setRequestType(String value) {
        setAttributeInternal(REQUESTTYPE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for REQUEST_REASON using the alias name RequestReason.
     * @return the REQUEST_REASON
     */
    public String getRequestReason() {
        return (String) getAttributeInternal(REQUESTREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_REASON using the alias name RequestReason.
     * @param value value to set the REQUEST_REASON
     */
    public void setRequestReason(String value) {
        setAttributeInternal(REQUESTREASON, value);
    }

    /**
     * Gets the attribute value for RESIGNATION_LETTER using the alias name ResignationLetter.
     * @return the RESIGNATION_LETTER
     */
    public String getResignationLetter() {
        return (String) getAttributeInternal(RESIGNATIONLETTER);
    }

    /**
     * Sets <code>value</code> as attribute value for RESIGNATION_LETTER using the alias name ResignationLetter.
     * @param value value to set the RESIGNATION_LETTER
     */
    public void setResignationLetter(String value) {
        setAttributeInternal(RESIGNATIONLETTER, value);
    }

    /**
     * Gets the attribute value for USER_ID_FK using the alias name UserIdFk.
     * @return the USER_ID_FK
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID_FK using the alias name UserIdFk.
     * @param value value to set the USER_ID_FK
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for ENTER_DATE using the alias name EnterDate.
     * @return the ENTER_DATE
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTER_DATE using the alias name EnterDate.
     * @param value value to set the ENTER_DATE
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for BRANCH_STATUS using the alias name BranchStatus.
     * @return the BRANCH_STATUS
     */
    public String getBranchStatus() {
        return (String) getAttributeInternal(BRANCHSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCH_STATUS using the alias name BranchStatus.
     * @param value value to set the BRANCH_STATUS
     */
    public void setBranchStatus(String value) {
        setAttributeInternal(BRANCHSTATUS, value);
    }

    /**
     * Gets the attribute value for DSS_STATUS using the alias name DssStatus.
     * @return the DSS_STATUS
     */
    public String getDssStatus() {
        return (String) getAttributeInternal(DSSSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for DSS_STATUS using the alias name DssStatus.
     * @param value value to set the DSS_STATUS
     */
    public void setDssStatus(String value) {
        setAttributeInternal(DSSSTATUS, value);
    }

    /**
     * Gets the attribute value for BRANCH_NOTIF_ID_FK using the alias name BranchNotifIdFk.
     * @return the BRANCH_NOTIF_ID_FK
     */
    public Number getBranchNotifIdFk() {
        return (Number) getAttributeInternal(BRANCHNOTIFIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCH_NOTIF_ID_FK using the alias name BranchNotifIdFk.
     * @param value value to set the BRANCH_NOTIF_ID_FK
     */
    public void setBranchNotifIdFk(Number value) {
        setAttributeInternal(BRANCHNOTIFIDFK, value);
    }

    /**
     * Gets the attribute value for DSS_NOTIF_ID_FK using the alias name DssNotifIdFk.
     * @return the DSS_NOTIF_ID_FK
     */
    public Number getDssNotifIdFk() {
        return (Number) getAttributeInternal(DSSNOTIFIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for DSS_NOTIF_ID_FK using the alias name DssNotifIdFk.
     * @param value value to set the DSS_NOTIF_ID_FK
     */
    public void setDssNotifIdFk(Number value) {
        setAttributeInternal(DSSNOTIFIDFK, value);
    }


    /**
     * Gets the attribute value for PERSON_TYPE using the alias name PersonType.
     * @return the PERSON_TYPE
     */
    public String getPersonType() {
        return (String) getAttributeInternal(PERSONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_TYPE using the alias name PersonType.
     * @param value value to set the PERSON_TYPE
     */
    public void setPersonType(String value) {
        setAttributeInternal(PERSONTYPE, value);
    }

    /**
     * Gets the attribute value for RESIGNATION_FILE using the alias name ResignationFile.
     * @return the RESIGNATION_FILE
     */
    public BlobDomain getResignationFile() {
        return (BlobDomain) getAttributeInternal(RESIGNATIONFILE);
    }

    /**
     * Sets <code>value</code> as attribute value for RESIGNATION_FILE using the alias name ResignationFile.
     * @param value value to set the RESIGNATION_FILE
     */
    public void setResignationFile(BlobDomain value) {
        setAttributeInternal(RESIGNATIONFILE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DssReqResigTermLineView.
     */
    public RowIterator getDssReqResigTermLineView() {
        return (RowIterator) getAttributeInternal(DSSREQRESIGTERMLINEVIEW);
    }


    /**
     * Gets the view accessor <code>RowSet</code> ResigTerminationPopList2.
     */
    public RowSet getResigTerminationPopList2() {
        return (RowSet) getAttributeInternal(RESIGTERMINATIONPOPLIST2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgentManagPopList1.
     */
    public RowSet getAgentManagPopList1() {
        return (RowSet) getAttributeInternal(AGENTMANAGPOPLIST1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> StipendPopList1.
     */
    public RowSet getStipendPopList1() {
        return (RowSet) getAttributeInternal(STIPENDPOPLIST1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UserBranchDtlLovVo1.
     */
    public RowSet getUserBranchDtlLovVo1() {
        return (RowSet) getAttributeInternal(USERBRANCHDTLLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgentDetailLovVo1.
     */
    public RowSet getAgentDetailLovVo1() {
        return (RowSet) getAttributeInternal(AGENTDETAILLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccLocationLov.
     */
    public RowSet getAccLocationLov() {
        return (RowSet) getAttributeInternal(ACCLOCATIONLOV);
    }
}

