package pqt.dss.rfrt.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 25 18:48:06 PKT 2016
// ---------------------------------------------------------------------
public interface DssReqResigTermHeaderView extends ViewObject {
    void setNVC_wfDocumentId(oracle.jbo.domain.Number value);

    void rfrtSearchUser();
}

