package pqt.dss.rfrt.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 20 11:33:14 PKT 2016
// ---------------------------------------------------------------------
public interface RfrtAM extends ApplicationModule {
    void Apply();


    void DssApprove();

    void Rollback();

    void DeleteCommit();

    void callWorkflow(oracle.jbo.domain.Number p_document_id, String ApprovalType);

    void callRFRTWorkflow(oracle.jbo.domain.Number p_document_id);
}

